### PR TITLE
Added an uninstall module

### PR DESCRIPTION
**Pull request by acxz**
Uninstall all files installed by the `sudo make install` command via `sudo make uninstall`

Note: Does not remove empty folders

### CODE REVIEW

**Comment by bluescarni** [comment]
@acxz Thanks for the PR! Would it be possible for you to add some code that exercises ``make uninstall`` in the CI? I was thinking perhaps installing in a custom prefix, uninstall and then verify that the files, apart from empty dirs, have been removed?

**Comment by acxz** [comment]
I actually have never used Travis CI, so I am not sure how to go about to do that. I would need to spend some time reading up how. Sadly, I currently do not have the time to do so.

**Comment by bluescarni** [comment]
Ok, I'll try to do it tonight then.

**Comment by bluescarni** [comment]
@acxz I did some local testing and it seems to be working fine. I'll go ahead and merge, and add the CI bits in another PR. Thanks!

**Pull request merged**
