### PR TITLE
Add hypervolume algorithm literature to python docs

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This adds literature already [contained in the CPP docs](https://esa.github.io/pagmo2/docs/cpp/utils/hypervolume.html#_CPPv2N5pagmo11hypervolumeE) on the underlying hypervolume algorithms to the Python docs and fixes an [unrendered problem formulation](https://esa.github.io/pagmo2/docs/python/tutorials/coding_udp_multi_objective.html) within the python tutorials.

### CODE REVIEW

**Comment by bluescarni** [comment]
Thanks for the PR!

The documentation build is failing because of some warnings like these:

https://travis-ci.org/esa/pagmo2/jobs/404074256#L1739

I believe there might be some indentation/whitespace problem in coding_udp_multi_objective.rst?

**Comment by ckaldemeyer** [comment]
> Thanks for the PR!
> 
> The documentation build is failing because of some warnings like these:
> 
> https://travis-ci.org/esa/pagmo2/jobs/404074256#L1739
> 
> I believe there might be some indentation/whitespace problem in coding_udp_multi_objective.rst?

It was the intendation indeed! Should be fixed with: https://github.com/esa/pagmo2/pull/194/commits/d4d733b78b7c4be0140ec7d62c26d4189eec8dc9 . Let's see if it makes Travis happy.. ;-)

**Comment by ckaldemeyer** [comment]
Hmm, two tests are not working:

1. https://travis-ci.org/esa/pagmo2/jobs/404891281
2. https://travis-ci.org/esa/pagmo2/jobs/404891288

Actually, I do not see why :-/

**Comment by bluescarni** [comment]
The first one looks like a transient failure, I'll take care of the second one in a separate PR. Merging, thanks!

**Pull request merged**
