### PR TITLE
fixed cstrs_self_adpative integer problem handling #465

### PR DESCRIPTION
**Pull request by SchwarzschildX**
made the changes and tested them. works.

### CODE REVIEW

**Comment by darioizzo** [comment]
Can you add a unit test for this? In https://github.com/esa/pagmo2/blob/master/tests/cstrs_self_adaptive.cpp ?
The test should fail in the old version and pass in the new version and should test all newly added lines.

**Comment by SchwarzschildX** [comment]
Sorry for the long delay. Just added a test to check the correct forwarding of the integer dimension from the udp to cstrs_self_adaptive.

CI tests fail, but not from my changes i guess:

CMake Error at cmake_modules/FindTBB.cmake:400 (file):
  file STRINGS file "/home/circleci/local/include/tbb/tbb_stddef.h" cannot be read.

**Comment by bluescarni** [comment]
@SchwarzschildX can you merge master into your branch?

**Comment by SchwarzschildX** [comment]
@bluescarni
Of course! Hope I did it right ;)

**Comment by bluescarni** [comment]
Thanks!

**Pull request merged**
