### PR TITLE
CMake: Workaround clang17+ / lto bug

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by bluescarni** [comment]
@jschueller thanks for the fast PR!

As far as I understand it, for the LLVM bug to trigger, link-time optimisation must be enabled - at least judging from this bugreport:

https://github.com/llvm/llvm-project/issues/71196

I was thus wondering if it would make sense to just disable LTO if clang>=17 is detected, rather than injecting the ``-fno-assume-unique-vtables``. I am not sure though, what do you think?

**Comment by jschueller** [comment]
lets keep the new flag, but only add it if IPO is enabled

**Comment by jschueller** [comment]
will close #579

**Comment by bluescarni** [comment]
@jschueller sorry for getting back to this only now...

As far as I understand from #586, switching off IPO actually did not prevent the bug from manifesting right? If that is the case and it is ok with you, I would slightly edit this PR to enable ``-fno-assume-unique-vtables`` regardless of whether or not IPO is enabled.

**Comment by bluescarni** [comment]
@jschueller thank you!

**Pull request merged**
