### PR TITLE
Fix for #382 (nan in hv computations)

### PR DESCRIPTION
**Pull request by darioizzo**
Should fix the problem of hv algorithms when nans are present (and m_verify is true)

### CODE REVIEW

**Comment by bluescarni** [comment]
There are two verification functions, ``verify_after_construct()`` and ``verify_before_compute()``. Do they both need the NaN check or is it sufficient in only one of them?

**Comment by darioizzo** [comment]
Yes, it some crazy overengineered verification code. Only the check after construction is needed in this case as that happens first and always (if m_verify is true).

**Comment by bluescarni** [comment]
Looks good to me, I'd like to wait for @ow97 to test the code before merging though, if possible.

**Comment by bluescarni** [comment]
Windows is complaining about the test code:

```
C:\projects\pagmo2\tests\hypervolume.cpp(219): error C2124: divide or mod by zero [C:\projects\pagmo2\build\tests\hypervolume.vcxproj]
```

Probably better to replace it with a ``quiet_NaN()`` I guess?

**Comment by ow97** [comment]
> Looks good to me, I'd like to wait for @ow97 to test the code before merging though, if possible.

I'll get back to you ASAP

**Comment by ow97** [comment]
I'm happy that throws an exception rather than segfaulting :+1:

**Comment by bluescarni** [comment]
> I'm happy that throws an exception rather than segfaulting +1

Just to be sure I understood correctly, does this mean that you tried the patch and it works fine for you?

**Comment by ow97** [comment]
> > I'm happy that throws an exception rather than segfaulting +1
> 
> Just to be sure I understood correctly, does this mean that you tried the patch and it works fine for you?

Yes it does. I am in favour of merging this PR :+1:

**Comment by bluescarni** [comment]
> Yes it does. I am in favour of merging this PR +1

Ok, thanks for the report and the testing! We'll probably do a 2.13 release within the week.

**Pull request merged**
